/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Messenger.Cliente;

import Messenger.Servidor.RemoteInterfaceMessenger;
import java.security.Key;

/**
 *
 * @author Ricardo
 */
public class MainGUI extends javax.swing.JFrame {

    MainGUI frame;
    Register reg;
    Login login;
    Chat chat;

    /**
     * Creates new form teste
     */
    public MainGUI() {
        initComponents();
        init();
    }

    public void chat() {
        frame.setSize(450, 660);
        login.setVisible(false);
        chat.setVisible(true);
        chat.setBounds(0, 0, 400, 460);
        chat.init();
    }

    public void reg() {
        frame.setSize(400, 360);
        login.setVisible(false);
        reg.setVisible(true);
        reg.setBounds(0, 0, 400, 290);
    }

    public void login() {
        //frame.setBounds(100, 100, 400, 360);
        frame.setSize(400, 360);
        reg.setVisible(false);
        chat.setVisible(false);
        login.setVisible(true);
        login.setBounds(0, 0, 400, 290);

    }

    public void start() {

        frame.setVisible(true);
        frame.setBounds(100, 100, 400, 360);
        reg.setVisible(false);
        chat.setVisible(false);
        login.setBounds(0, 0, 400, 230);
        login.setVisible(true);
        frame.add(login);
        frame.add(reg);
        frame.add(chat);

        login();
    }

    public MainGUI getFrame() {
        return frame;
    }

    public Register getReg() {
        return reg;
    }

    public Login getLogin() {
        return login;
    }

    public Chat getChat() {
        return chat;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI();
            }
        });
    }

    public void init() {
        frame = this;
        login = new Login(frame);
        reg = new Register(frame);
        chat = new Chat(frame);
        frame.start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
