/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Messenger.Cliente;

import Messenger.Servidor.RemoteInterfaceMessenger;
import Messenger.Utils.Secrets;
import Messenger.Utils.Serializer;
import java.security.Key;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Ricardo
 */
public class RetrievePass extends javax.swing.JFrame {

    /**
     * Creates new form RetrievePass
     */
    Login login;
    RemoteInterfaceMessenger remote;
    Key sharedKey;

    public RetrievePass(Login login) {
        this.login = login;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_Username_Ret = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_Question_Ret = new javax.swing.JTextField();
        lbl_question = new javax.swing.JLabel();
        lbl_answer = new javax.swing.JLabel();
        txt_Answer_Ret = new javax.swing.JTextField();
        btn_next = new javax.swing.JButton();
        btn_confirm = new javax.swing.JButton();
        lbl_password = new javax.swing.JLabel();
        txt_Password_Ret = new javax.swing.JTextField();
        btn_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Username:");

        txt_Question_Ret.setEditable(false);
        txt_Question_Ret.setEnabled(false);

        lbl_question.setText("Question:");
        lbl_question.setEnabled(false);

        lbl_answer.setText("Answer:");
        lbl_answer.setEnabled(false);

        txt_Answer_Ret.setEnabled(false);

        btn_next.setText("Next");
        btn_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nextActionPerformed(evt);
            }
        });

        btn_confirm.setText("Confirm");
        btn_confirm.setEnabled(false);
        btn_confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_confirmActionPerformed(evt);
            }
        });

        lbl_password.setText("Password:");
        lbl_password.setEnabled(false);

        txt_Password_Ret.setEditable(false);
        txt_Password_Ret.setEnabled(false);
        txt_Password_Ret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Password_RetActionPerformed(evt);
            }
        });

        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_back))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_confirm)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_question)
                                    .addComponent(lbl_answer)
                                    .addComponent(lbl_password))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt_Username_Ret, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_next)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txt_Answer_Ret)
                                    .addComponent(txt_Question_Ret)
                                    .addComponent(txt_Password_Ret))))))
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Username_Ret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btn_next))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Question_Ret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_question))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_answer)
                    .addComponent(txt_Answer_Ret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_confirm)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_password)
                    .addComponent(txt_Password_Ret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_back)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
        // TODO add your handling code here:
        login.init();
        this.remote = login.remote;
        this.sharedKey = login.sharedKey;

        if (!txt_Username_Ret.getText().equals("")) {
            try {
                byte[] user = Secrets.encrypt(Serializer.toByteArray(txt_Username_Ret.getText()), sharedKey);
                String question = (String) Serializer.toObject(Secrets.decrypt(remote.getQuestion(user), sharedKey));
                if (question != null) {
                    lbl_question.setEnabled(true);
                    lbl_answer.setEnabled(true);
//                    lbl_password.setEnabled(true);
                    txt_Answer_Ret.setEnabled(true);
                    txt_Question_Ret.setEnabled(true);
//                    txt_Password_Ret.setEnabled(true);
                    btn_confirm.setEnabled(true);
                    txt_Question_Ret.setText(question);
                }
            } catch (Exception ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_btn_nextActionPerformed

    private void btn_confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_confirmActionPerformed
        if (!txt_Answer_Ret.getText().equals("")) {
            try {
                byte[] user = Secrets.encrypt(Serializer.toByteArray(txt_Username_Ret.getText()), sharedKey);
                byte[] ans = Secrets.encrypt(Serializer.toByteArray(txt_Answer_Ret.getText()), sharedKey);

                if (remote.correctAns(user, ans)) {
                    String passF = (String) Serializer.toObject(Secrets.decrypt(remote.getPass(user), sharedKey));
                    lbl_password.setEnabled(true);
                    txt_Password_Ret.setEnabled(true);
                    txt_Password_Ret.setText(passF);
                } else {
                    lbl_password.setEnabled(false);
                    txt_Password_Ret.setEnabled(true);
                    txt_Password_Ret.setText("The answer is invalid!");
                }
            } catch (Exception ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_confirmActionPerformed

    private void txt_Password_RetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Password_RetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Password_RetActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        this.setVisible(false);
        this.login.setVisible(true);
    }//GEN-LAST:event_btn_backActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_confirm;
    private javax.swing.JButton btn_next;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_answer;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_question;
    private javax.swing.JTextField txt_Answer_Ret;
    private javax.swing.JTextField txt_Password_Ret;
    private javax.swing.JTextField txt_Question_Ret;
    private javax.swing.JTextField txt_Username_Ret;
    // End of variables declaration//GEN-END:variables
}
